name: etoolbox
channels:
  - conda-forge
dependencies:
  # Packages required for setting up the environment
  - pip>=21,<23
  #  - python>=3.10,<3.12  # this should allow testing multiple versions
  - setuptools<66

  # Packages specified in setup.cfg that need or benefit from binary conda packages
  - pandas >= 1.4,<1.6
  - pyarrow>=9, <11

  # Use pip to install the package defined by this repo for development:
  - pip:
      - --editable ./[dev,doc,tests]
