name: cheshire
channels:
  - conda-forge
dependencies:
  # Packages required for setting up the environment
  - pip>=21,<23
  - python>=3.8,<3.11
  - setuptools<64

  # Packages specified in setup.cfg that need or benefit from binary conda packages
  - bottleneck ~= 1.3
  - numexpr ~= 2.8
  - numpy >= 1.18.5,<2
  - pandas >= 1.4,<1.5

  # Packages not specified in setup.cfg that provide optional, helpful binaries:
  # - numba>=0.55.1,<0.56  # numba speeds up some kinds of math by 100x

  # Jupyter packages:
  - jupyterlab>=3.2,<4
  - nbconvert>=6,<7 # Used to clear notebook outputs in pre-commit hooks

  # Use pip to install the package defined by this repo for development:
  - pip:
      - --editable ./[dev,doc,tests,types]
