name: tox-pytest-pudl

on: [push]

jobs:
  ci-test:
    name: pudl-test ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest", "windows-latest"]
      fail-fast: false

    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Install Conda environment using mamba
        uses: mamba-org/provision-with-micromamba@v15
        with:
          environment-file: tests/pudl-test-env.yml
          cache-env: true
          channels: conda-forge
          channel-priority: strict

      - name: Log environment details
        run: |
          conda info
          conda list
          conda config --show-sources
          conda config --show
          printenv | sort

      - name: Run unit tests with Tox
        run: |
          tox -e pudl
